-- lua/plugins/ ディレクトリ
-- このディレクトリに *.lua ファイルを追加することでプラグインを追加できる
--
-- 追加予定:
--   ui.lua         : カラースキーム、ステータスライン等
--   lsp.lua        : mason.nvim + nvim-lspconfig
--   completion.lua : nvim-cmp
--   lang/java.lua  : nvim-java
--
-- 各ファイルは以下の形式でプラグイン定義を返す:
--
-- return {
--   {
--     "plugin/name",
--     event = "VeryLazy",  -- lazy loadのトリガー
--     opts = {},            -- setupに渡すオプション
--   },
-- }

-- このファイル自身はプラグインなし（プレースホルダー）
return {}
